--drop database [dbQUANLYBANHANGONLINE]
--create database [dbQUANLYBANHANGONLINE]
go
--USE [dbQUANLYBANHANGONLINE]

go

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--  Object: Table [dbo].[APPLICATIONS]
CREATE TABLE [dbo].[APPLICATIONS](
[ID_APPLICATION] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
[APPLICATION_NAME] [nvarchar](100) NULL,
[DESCRIPTION] [nvarchar](255) NULL,
CONSTRAINT [PK_APPLICATIONS] PRIMARY KEY CLUSTERED
(
[ID_APPLICATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[APPLICATIONS_MENU_FORM_RELATIONS]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS](
[ID_MENU_FORM] [numeric](18, 0) NOT NULL,
[ID_APPLICATION] [numeric](18, 0) NOT NULL,
CONSTRAINT [PK_APPLICATIONS_MENU_FORM_RELATIONS] PRIMARY KEY CLUSTERED
(
[ID_MENU_FORM] ASC,
[ID_APPLICATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[GENDER]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GENDER](
[PARTY_ID] [numeric](18, 0) NOT NULL,
[GENDER_TYPE_ID] [numeric](18, 0) NOT NULL,
[FROM_DATE] [datetime] NOT NULL,
[THRU_DATE] [datetime] NULL,
CONSTRAINT [PK__GENDER__3F865F66] PRIMARY KEY CLUSTERED
(
[PARTY_ID] ASC,
[GENDER_TYPE_ID] ASC,
[FROM_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Table [dbo].[GENDER_TYPE]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GENDER_TYPE](
[GENDER_TYPE_ID] [numeric](18, 0) NOT NULL,
[GENDER_TYPE_NAME] [nvarchar](10) NOT NULL,
[DESCRIPTION] [varchar](255) NULL,
CONSTRAINT [PK__GENDER_TYPE__3D9E16F4] PRIMARY KEY CLUSTERED
(
[GENDER_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- Table [dbo].[GROUP_RELATIONSHIP_MENU_FORM]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM](
[PARTY_ID] [numeric](18, 0) NOT NULL,
[ID_GROUP] [numeric](18, 0) NOT NULL,
[ID_MENU_FORM] [numeric](18, 0) NOT NULL,
CONSTRAINT [PK_GROUP_RELATIONSHIP_MENU_FORM] PRIMARY KEY CLUSTERED
(
[PARTY_ID] ASC,
[ID_GROUP] ASC,
[ID_MENU_FORM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Table [dbo].[GROUP_USER]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP_USER](
[ID_GROUP] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
[GROUP_NAME] [nvarchar](300) NULL,
[DESCRIPTION] [nvarchar](1000) NULL,
CONSTRAINT [PK_GROUP_USER] PRIMARY KEY CLUSTERED
(
[ID_GROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[GROUP_USER_RELATIONSHIP_USER]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER](
[PARTY_ID] [numeric](18, 0) NOT NULL,
[ID_GROUP] [numeric](18, 0) NOT NULL,
CONSTRAINT [PK_GROUP_USER_RELATIONSHIP_USER_1] PRIMARY KEY CLUSTERED
(
[PARTY_ID] ASC,
[ID_GROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[MENU_FORM]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MENU_FORM](
[ID_MENU_FORM] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
[MENU_FORM_NAME] [nvarchar](300) NULL,
[MENU_FORM_URL] [varchar](50) NULL,
[MOTA] [nvarchar](500) NULL,
[SORT_PARENT] [tinyint] NULL,
[SORT] [tinyint] NULL,
[ID_MENU_FORM_PARENT] [numeric](18, 0) NULL,
[DANH_MUC] [bit] NULL,
[VISIBLE] [bit] NULL,
CONSTRAINT [PK_MENU_FORM] PRIMARY KEY CLUSTERED
(
[ID_MENU_FORM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- Object: Table [dbo].[PARTY]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTY](
[PARTY_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
[TYPE_OF_PARTY] [nvarchar](50) NOT NULL,
[DEPARTMENT_ID] [int] NULL,
[USERNAME] [nvarchar](20) NULL,
[PASSWORD] [nvarchar](20) NULL,
[USERNAME_H] [nvarchar](300) NULL,
[PASSWORD_H] [nvarchar](300) NULL,
CONSTRAINT [PK_PARTY_1] PRIMARY KEY CLUSTERED
(
[PARTY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[PERSON]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSON](
[PARTY_ID] [numeric](18, 0) NOT NULL,
[CURRENT_LAST_NAME] [nvarchar](50) NULL,
[CURRENT_FIRST_NAME] [nvarchar](50) NULL,
[CURRENT_MIDDLE_NAME] [nvarchar](50) NULL,
[CURRENT_NICKNAME] [nvarchar](50) NULL,
[CURRENT_GENDER_TYPE_ID] [numeric](18, 0) NULL,
[BIRTH_DATE] [datetime] NULL,
[PEOPLE_ID_NUMBER] [nvarchar](50) NULL,
[PEOPLE_ID_ISSUE_DATE] [datetime] NULL,
[PEOPLE_ID_ISSUE_PLACE] [nvarchar](50) NULL,
[CURRENT_PHONE_NUMBER] [nvarchar](100) NULL,
[CURRENT_EMAIL] [nvarchar](100) NULL,
[PERSON_IMAGE] [nvarchar](50) NULL,
CONSTRAINT [PK_PERSON] PRIMARY KEY CLUSTERED
(
[PARTY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[tbCHITIETHOADON]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbCHITIETHOADON](
[MACHITIET] [int] IDENTITY(1,1) NOT NULL,
[MASANPHAM] [int] NULL,
[SOLUONG] [numeric](18, 0) NULL,
[DONGIA] [numeric](18, 0) NULL,
[MAHOADON] [int] NULL,
CONSTRAINT [PK_tbCHITIETHOADON] PRIMARY KEY CLUSTERED
(
[MACHITIET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[tbDANHMUC]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbDANHMUC](
[MADANHMUC] [int] IDENTITY(1,1) NOT NULL,
[TENDANHMUC] [nvarchar](200) NULL,
[DANHMUCCHA] [int] NULL,
[MOTA] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED
(
[MADANHMUC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[tbHOADON]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbHOADON](
[MAHOADON] [int] NOT NULL,
[MAKHACHHANG] [numeric](18, 0) NULL,
[NGAY] [datetime] NULL,
[TONGTIEN] [numeric](18, 0) NULL,
CONSTRAINT [PK_tbHOADON] PRIMARY KEY CLUSTERED
(
[MAHOADON] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Object: Table [dbo].[tbKHANHHANG]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbKHANHHANG](
[MAKHACHHANG] [numeric](18, 0) NOT NULL,
[HOTEN] [nvarchar](50) NULL,
[NGAYSINH] [date] NULL,
[GIOITINH] [nvarchar](6) NULL,
[EMAIL] [nchar](10) NULL,
[DIACHI] [nvarchar](200) NULL,
[TAIKHOAN] [nvarchar](50) NULL,
[MATKHAU] [nvarchar](50) NULL,
CONSTRAINT [PK_tbKHANHHANG] PRIMARY KEY CLUSTERED
(
[MAKHACHHANG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

--  Object: Table [dbo].[tbSANPHAM]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbSANPHAM](
[MASANPHAM] [int] IDENTITY(1,1) NOT NULL,
[TENSANPHAM] [nvarchar](200) NULL,
[DONGIA] [numeric](18, 0) NULL,
[SOLUONG] [numeric](18, 0) NULL,
[HINHANH] [nvarchar](50) NULL,
[MOTA] [nvarchar](max) NULL,
[MADANHMUC] [int] NULL,
PRIMARY KEY CLUSTERED
(
[MASANPHAM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[tbDANHMUC] ON
GO




-- Insert data
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (1,
N'Máy vi tính', 0, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (2,
N'LapTop', 1, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (3,
N'Điện Thoại', 0, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (4,
N'Iphome', 2, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (5,
N'SamSung', 2, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (6,
N'Ti vi', 0, NULL)
GO
INSERT [dbo].[tbDANHMUC] ([MADANHMUC], [TENDANHMUC], [DANHMUCCHA], [MOTA]) VALUES (7,
N'Sony', 5, NULL)
GO
SET IDENTITY_INSERT [dbo].[tbDANHMUC] OFF
GO
SET IDENTITY_INSERT [dbo].[tbSANPHAM] ON
GO

INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH],
[MOTA], [MADANHMUC]) VALUES (7, N'Laptop Dell Vostro 3420 I5', CAST(2000 AS Numeric(18,
0)), CAST(10 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 
GHz, 8MB)
RAM: 8GB(8GBx1) DDR4 3200MHz (2 khe)
Ổ cứng: 256GB M.2 256GB PCIe NVMe + 1x2.5"(HDD/SSD)
VGA: Intel Iris Xe Graphics', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH],
[MOTA], [MADANHMUC]) VALUES (8, N'THINKPAD W510 i7 EXTREME', CAST(300 AS Numeric(18, 0)),
CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 GHz, 
8MB)
RAM: 8GB(8GBx1) DDR4 3200MHz (2 khe)
Ổ cứng: 256GB M.2 256GB PCIe NVMe + 1x2.5"(HDD/SSD)
VGA: Intel Iris Xe Graphics', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH],
[MOTA], [MADANHMUC]) VALUES (9, N'THINKPAD W510 i7 EXTREME', CAST(300 AS Numeric(18, 0)),
CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 GHz, 
8MB)', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH],
[MOTA], [MADANHMUC]) VALUES (10, N'THINKPAD W510 i7 EXTREME', CAST(500 AS Numeric(18,
0)), CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 
GHz, 8MB)', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH],
[MOTA], [MADANHMUC]) VALUES (11, N'Laptop Dell Vostro 3420 I5', CAST(300 AS Numeric(18,
0)), CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 
GHz, 8MB)', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH],
[MOTA], [MADANHMUC]) VALUES (12, N'Laptop Dell Vostro 3420 I5', CAST(100 AS Numeric(18,
0)), CAST(1 AS Numeric(18, 0)), N'laptop.gif', N'CPU: Intel® Core i5-1135G7 (upto 4.20 
GHz, 8MB)', 1)
GO
INSERT [dbo].[tbSANPHAM] ([MASANPHAM], [TENSANPHAM], [DONGIA], [SOLUONG], [HINHANH],
[MOTA], [MADANHMUC]) VALUES (53, N'Samsung S10', CAST(430000 AS Numeric(18, 0)), CAST(111 
AS Numeric(18, 0)), N'SAMSUNG2.jfif', N'Samsung Galaxy S10 là chiếc smartphone kỉ niệm 10 năm ngày 
kể từ ngày đầu tiên Samsung ra mắt chiếc Galaxy S và không phụ sự chờ đợi của người dùng thì Samsung 
Galaxy S10 thực sự rất ấn tượng.', 3)
GO
SET IDENTITY_INSERT [dbo].[tbSANPHAM] OFF
GO

-- Add Constraint
ALTER TABLE [dbo].[MENU_FORM] ADD CONSTRAINT [DF_MENU_FORM_DANH_MUC] DEFAULT ((0)) FOR
[DANH_MUC]
GO
ALTER TABLE [dbo].[MENU_FORM] ADD CONSTRAINT [DF_MENU_FORM_VISIBLE] DEFAULT ((1)) FOR
[VISIBLE]
GO
ALTER TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS] WITH CHECK ADD CONSTRAINT
[FK_APPLICATIONS_MENU_FORM_RELATIONS_APPLICATIONS] FOREIGN KEY([ID_APPLICATION])
REFERENCES [dbo].[APPLICATIONS] ([ID_APPLICATION])
GO
ALTER TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS] CHECK CONSTRAINT
[FK_APPLICATIONS_MENU_FORM_RELATIONS_APPLICATIONS]
GO
ALTER TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS] WITH CHECK ADD CONSTRAINT
[FK_APPLICATIONS_MENU_FORM_RELATIONS_MENU_FORM] FOREIGN KEY([ID_MENU_FORM])
REFERENCES [dbo].[MENU_FORM] ([ID_MENU_FORM])
GO
ALTER TABLE [dbo].[APPLICATIONS_MENU_FORM_RELATIONS] CHECK CONSTRAINT
[FK_APPLICATIONS_MENU_FORM_RELATIONS_MENU_FORM]
GO
ALTER TABLE [dbo].[GENDER] WITH CHECK ADD CONSTRAINT [ FK__GENDER__GENDER_T__416EA7D8]
FOREIGN KEY([GENDER_TYPE_ID])
REFERENCES [dbo].[GENDER_TYPE] ([GENDER_TYPE_ID])
GO
ALTER TABLE [dbo].[GENDER] CHECK CONSTRAINT [ FK__GENDER__GENDER_T__416EA7D8]
GO
ALTER TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM] WITH CHECK ADD CONSTRAINT
[FK_GROUP_RELATIONSHIP_MENU_FORM_GROUP_USER_RELATIONSHIP_USER] FOREIGN KEY([PARTY_ID],
[ID_GROUP])
REFERENCES [dbo].[GROUP_USER_RELATIONSHIP_USER] ([PARTY_ID], [ID_GROUP])
GO
ALTER TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM] CHECK CONSTRAINT
[FK_GROUP_RELATIONSHIP_MENU_FORM_GROUP_USER_RELATIONSHIP_USER]
GO
ALTER TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM] WITH CHECK ADD CONSTRAINT
[FK_GROUP_RELATIONSHIP_MENU_FORM_MENU_FORM] FOREIGN KEY([ID_MENU_FORM])
REFERENCES [dbo].[MENU_FORM] ([ID_MENU_FORM])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GROUP_RELATIONSHIP_MENU_FORM] CHECK CONSTRAINT
[FK_GROUP_RELATIONSHIP_MENU_FORM_MENU_FORM]
GO
ALTER TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER] WITH CHECK ADD CONSTRAINT
[FK_GROUP_USER_RELATIONSHIP_USER_GROUP_USER] FOREIGN KEY([ID_GROUP])
REFERENCES [dbo].[GROUP_USER] ([ID_GROUP])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER] CHECK CONSTRAINT
[FK_GROUP_USER_RELATIONSHIP_USER_GROUP_USER]
GO
ALTER TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER] WITH CHECK ADD CONSTRAINT
[FK_GROUP_USER_RELATIONSHIP_USER_PARTY] FOREIGN KEY([PARTY_ID])
REFERENCES [dbo].[PARTY] ([PARTY_ID])
GO
ALTER TABLE [dbo].[GROUP_USER_RELATIONSHIP_USER] CHECK CONSTRAINT
[FK_GROUP_USER_RELATIONSHIP_USER_PARTY]
GO
ALTER TABLE [dbo].[MENU_FORM] WITH CHECK ADD CONSTRAINT [FK_MENU_FORM_MENU_FORM]
FOREIGN KEY([ID_MENU_FORM_PARENT])
REFERENCES [dbo].[MENU_FORM] ([ID_MENU_FORM])
GO
ALTER TABLE [dbo].[MENU_FORM] CHECK CONSTRAINT [FK_MENU_FORM_MENU_FORM]
GO
ALTER TABLE [dbo].[PERSON] WITH CHECK ADD CONSTRAINT [FK_PERSON_PARTY] FOREIGN
KEY([PARTY_ID])
REFERENCES [dbo].[PARTY] ([PARTY_ID])
GO
ALTER TABLE [dbo].[PERSON] CHECK CONSTRAINT [FK_PERSON_PARTY]
GO
ALTER TABLE [dbo].[tbCHITIETHOADON] WITH CHECK ADD CONSTRAINT
[FK_tbCHITIETHOADON_tbHOADON] FOREIGN KEY([MAHOADON])
REFERENCES [dbo].[tbHOADON] ([MAHOADON])
GO
ALTER TABLE [dbo].[tbCHITIETHOADON] CHECK CONSTRAINT [FK_tbCHITIETHOADON_tbHOADON]
GO
ALTER TABLE [dbo].[tbCHITIETHOADON] WITH CHECK ADD CONSTRAINT
[FK_tbCHITIETHOADON_tbSANPHAM] FOREIGN KEY([MASANPHAM])
REFERENCES [dbo].[tbSANPHAM] ([MASANPHAM])
GO
ALTER TABLE [dbo].[tbCHITIETHOADON] CHECK CONSTRAINT [FK_tbCHITIETHOADON_tbSANPHAM]
GO
ALTER TABLE [dbo].[tbHOADON] WITH CHECK ADD CONSTRAINT [FK_tbHOADON_PARTY] FOREIGN
KEY([MAKHACHHANG])
REFERENCES [dbo].[PARTY] ([PARTY_ID])
GO
ALTER TABLE [dbo].[tbHOADON] CHECK CONSTRAINT [FK_tbHOADON_PARTY]
GO
ALTER TABLE [dbo].[tbHOADON] WITH CHECK ADD CONSTRAINT [FK_tbHOADON_tbKHANHHANG]
FOREIGN KEY([MAKHACHHANG])
REFERENCES [dbo].[tbKHANHHANG] ([MAKHACHHANG])
GO
ALTER TABLE [dbo].[tbHOADON] CHECK CONSTRAINT [FK_tbHOADON_tbKHANHHANG]
GO
ALTER TABLE [dbo].[tbSANPHAM] WITH CHECK ADD CONSTRAINT [FK_tbSANPHAM_tbDANHMUC]
FOREIGN KEY([MADANHMUC])
REFERENCES [dbo].[tbDANHMUC] ([MADANHMUC])
GO
ALTER TABLE [dbo].[tbSANPHAM] CHECK CONSTRAINT [FK_tbSANPHAM_tbDANHMUC]
GO

CREATE Proc [dbo].[psGetTableSANPHAM] (@MASANPHAM INT)
as
BEGIN TRAN
IF(@MASANPHAM is null)
select * from tbSANPHAM
ELSE
select * from tbSANPHAM where MASANPHAM = @MASANPHAM
IF(@@ERROR<>0)
	ROLLBACK TRAN
ELSE
COMMIT TRAN

CREATE PROC [dbo].[psGettableDANHMUC](@MADANHMUC INT)
AS
BEGIN TRAN
IF (@MADANHMUC IS NULL)
SELECT ROW_NUMBER() OVER(ORDER BY tendanhmuc) as autoincrement, MADANHMUC,tendanhmuc, danhmuccha FROM tbDANHMUC
ELSE
SELECT * FROM tbDANHMUC WHERE MADANHMUC = @MADANHMUC
IF (@@ERROR <> 0)
ROLLBACK TRAN
ELSE
COMMIT TRAN


create proc [dbo].[psgetTableLOGIN] (@USERNAME NVARCHAR(30),@PASSWORD NVARCHAR(30))
AS
BEGIN TRAN
SELECT * FROM PARTY WHERE USERNAME=@USERNAME AND PASSWORD=@PASSWORD
IF(@@ERROR <>0)
	ROLLBACK TRAN
ELSE
COMMIT TRAN

insert into dbo.PARTY(TYPE_OF_PARTY, DEPARTMENT_ID,USERNAME,[PASSWORD],USERNAME_H,PASSWORD_H)
values (N'PNam', 2, 'admin', '123', null, null);

select *
from PARTY

create proc [dbo].[psInsertRecordSANPHAM] (@TENSANPHAM NVARCHAR(300),
@DONGIA numeric(18,0),
@SOLUONG INT, @HINHANH nvarchar(50), @MOTA nvarchar(MAX), @MADANHMUC INT)
AS
BEGIN TRAN
INSERT INTO tbSANPHAM(TENSANPHAM,DONGIA,SOLUONG,HINHANH,MOTA,MADANHMUC)
VALUES (@TENSANPHAM,@DONGIA,@SOLUONG,@HINHANH,@MOTA,@MADANHMUC)
IF(@@ERROR<>0)
	ROLLBACK TRAN
ELSE
COMMIT TRAN

CREATE PROC [dbo].[psUpdateRecordSANPHAM](@MASANPHAM INT, @TENSANPHAM NVARCHAR(300),@DONGIA numeric(18,0),
@SOLUONG INT, @HINHANH NVARCHAR(50), @MOTA NVARCHAR(MAX), @MADANHMUC INT)
AS
BEGIN TRAN
UPDATE tbSANPHAM SET TENSANPHAM=@TENSANPHAM, DONGIA=@DONGIA, SOLUONG=@SOLUONG, HINHANH=@HINHANH, MOTA=@MOTA, MADANHMUC=@MADANHMUC
WHERE MASANPHAM=tbSANPHAM.MASANPHAM

IF(@@ERROR<>0)
	ROLLBACK TRAN
ELSE
COMMIT TRAN


create proc [dbo].[psDeleteRecordSANPHAM] (@MASANPHAM INT)
AS
BEGIN TRAN
DELETE FROM tbSANPHAM WHERE MASANPHAM = @MASANPHAM
IF(@@ERROR <> 0)
	ROLLBACK TRAN
ELSE
	COMMIT TRAN
select *
from tbSANPHAM